### ISSUE TITLE
Not able to login using Admin

### ISSUE THREAD

**Issue by atinprominic** [aKn1ghtOut/Quiznode#1]
Hi

The installation was done successfull but I am not able to login from the Admin account

Thanks

**Comment by aKn1ghtOut** [comment]
Please add the complete list of actions you took chronologically, so I could help you better.
Maybe read the README again. Did you edit the ex.htaccess and make it .htaccess since you're using a subfolder for installation. You would also need to edit the variables in the config file according to the instructions provided there.
